---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Installation & Configuration"
      solveButton: false
    - name: module-02
      label: "Understanding Audit Logs"
      solveButton: false
    - name: module-03
      label: "Creating Watch Rules"
      solveButton: false
    - name: module-04
      label: "Preconfigured Rules"
      solveButton: false
    - name: module-05
      label: "Custom Rule Creation"
      solveButton: false
    - name: module-06
      label: "Generating Reports"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty

